image: mcr.microsoft.com/dotnet/sdk:5.0

tasks:
  - name: DOTNET
  - init: |
          cp -r /usr/share/dotnet /workspace
          dotnet restore
    command: /workspace/dotnet/dotnet watch run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

